export { default as Alarm } from './Alarm.svg?react';
export { default as AmazonConnectIcon } from './AmazonConnect.svg?react';
export { default as ArrowBackIos } from './ArrowBackIos.svg?react';
export { default as ArrowForwardIos } from './ArrowForwardIos.svg?react';
export { default as BarChart } from './BarChart.svg?react';
export { default as CalendarToday } from './CalendarToday.svg?react';
export { default as CallEnd } from './CallEnd.svg?react';
export { default as Cancel } from './Cancel.svg?react';
export { default as Check } from './Check.svg?react';
export { default as CheckCircle } from './CheckCircle.svg?react';
export { default as CheckCircleFill } from './CheckCircleFill.svg?react';
export { default as ClearNight } from './ClearNight.svg?react';
export { default as Close } from './Close.svg?react';
export { default as Done } from './Done.svg?react';
export { default as Exercise} from './Exercise.svg?react';
export { default as InstantMix } from './InstantMix.svg?react';
export { default as KeyboardReturn } from './KeyboardReturn.svg?react';
export { default as Logout } from './Logout.svg?react';
export { default as Menu } from './Menu.svg?react';
export { default as Mitre } from './Mitre.svg?react';
export { default as MoveDown } from './MoveDown.svg?react';
export { default as PhoneInTalk } from './PhoneInTalk.svg?react';
export { default as RadioButtonUnchecked } from './RadioButtonUnchecked.svg?react';
export { default as SearchFill } from './SearchFill.svg?react';
export { default as SentimentDissatisfied } from './SentimentDissatisfied.svg?react';
export { default as SocialLeaderboard } from './SocialLeaderboard.svg?react';
export { default as SupportAgent } from './SupportAgent.svg?react';
export { default as Visibility } from './Visibility.svg?react';
export { default as VisibilityOff } from './VisibilityOff.svg?react';
export { default as Warning } from './Warning.svg?react';
export {default as ExpandLess} from './ExpandLess.svg?react';
export {default as ExpandMore} from './ExpandMore.svg?react';
